<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.12" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.12" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.12" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.12" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.12">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Dapper" Version="2.1.72" />
        <PackageReference Include="DotNetEnv" Version="3.1.1" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
        <PackageReference Include="Npgsql" Version="10.0.2" />
        <PackageReference Include="dbup-postgresql" Version="5.0.39" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Scripts\*.sql"/>
    </ItemGroup>

    <!-- Staré soubory vyloučené z kompilace -->
    <ItemGroup>
        <Compile Remove="MainViewModel.cs"/>
        <Compile Remove="ObservableObject.cs"/>
        <Compile Remove="TodoItem.cs"/>
        <Compile Remove="ITodoRepository.cs"/>
        <Compile Remove="TodoRepository.cs"/>
    </ItemGroup>
</Project>
